add_newline = false

format = """
$username\
$hostname\
$container\
$directory\
$git_branch\
$git_status\
$character
"""

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "î‚  "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[character]
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[âœ](red)"

[hostname]
format='[$ssh_symbol$hostname]($style):'
ssh_symbol ="ğŸŒ"
[username]
format='[$user]($style)'

[container]
format = "[$symbol $name]($style) "
symbol = "ğŸ³"
style = "bold blue"
